name: Build and Deploy ASP.NET App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Publish the project
      run: dotnet publish --configuration Release --output ./publish

    # Azure login action
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        azure-sp-app-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-sp-password: ${{ secrets.AZURE_CLIENT_SECRET }}
        azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}

    # Deploy to Azure App Service
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'MyAspNetApp2603'  # Replace with your Azure App Service name
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: './publish'  # Path to the published output
